version: 2

sources:
  - name: fetch_raw_data
    description: fetch app relevant data
    database: "{{ env_var(DBT_ENV_CUSTOM_ENV_INGEST_DATABASE)}}"
    schema: FETCH_RAW_SCHEMA

    tables:
      - name: receipts
        description: Stores information about each receipt.
        columns:
          - name: _id
            description: Unique identifier for each receipt
            column_type: INTEGER
            tests:
              - not_null
              - unique
              
      - name: brands
        description:  Information related to products purchased
        columns:
          - name: _id
            description: Unique identifier for each product
            column_type: INTEGER
            tests:
              - not_null
              - unique
              
      - name: users
        description:  Information related to the user who made the purchase.
        columns:
          - name: _id
            description: Unique identifier for each user
            column_type: INTEGER
            tests:
              - not_null
              - unique
